import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  tag: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    width: "auto",
    height: 48,
    backgroundColor: theme.palette.secondary.main,
    borderRadius: "3px 4px 4px 3px",
    borderLeft: `1px solid ${theme.palette.secondary.main}`,
    marginLeft: 19,
    position: "relative",
    color: "white",
    fontWeight: 300,
    fontSize: 22,
    lineHeight: 38,
    padding: "0 10px 0 10px",
    "& h4": {
      fontFamily: "Satisfy",
      fontWeight: 700,
      marginTop: 5,
    },
    "&::before": {
      content: "''",
      position: "absolute",
      display: "block",
      left: -19,
      width: 0,
      height: 0,
      borderTop: "25px solid transparent",
      borderBottom: "23px solid transparent",
      borderRight: `19px solid ${theme.palette.secondary.main}`,
    },
    "&::after": {
      content: "''",
      backgroundColor: "white",
      borderRadius: "50%",
      width: 4,
      height: 4,
      display: "block",
      position: "absolute",
      left: -6,
      top: 21,
    },
  },
}));
